apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: blog-ingressroute
  namespace: blog
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`blog.lucasferraz.cloud`)
      kind: Rule
      services:
        - name: blog-app
          port: 8080
  tls:
    secretName: blog-certificate-secret
