apiVersion: v1
kind: Service
metadata:
  name: blog-app
  namespace: blog
spec:
  type: NodePort
  selector:
    app: blog-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31001
